AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  Author: cesardramirez
  Descriotion: Plantilla básica con recurso IAM
  Version: '1.0'
Resources:
  UserIAM:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: ydiazp_yml
